name: hoctapflutter
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  flutter_bloc: ^9.0.0
  shared_preferences: ^2.5.3
  easy_localization: ^3.0.8

  supabase_flutter: ^2.10.0

  realm: ^20.1.1

  equatable: ^2.0.7
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.8
  http: any
  go_router: ^14.8.1
dev_dependencies:
  flutter_native_splash: ^2.4.0
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logos/todo-list-icon.png"
  adaptive_icon_background: "#1976D2"
  adaptive_icon_foreground: "assets/logos/icon_android.png"

  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
      - assets/images/
      - assets/logos/
      - assets/translations/
  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Black.ttf
          weight: 300
        - asset: assets/fonts/Lato-ThinItalic.ttf
          weight: 100
        - asset: assets/fonts/Lato-Thin.ttf
          weight: 100
        - asset: assets/fonts/Lato-Regular.ttf
          weight: 400
        - asset: assets/fonts/Lato-LightItalic.ttf
          weight: 300
        - asset: assets/fonts/Lato-Light.ttf
          weight: 300
        - asset: assets/fonts/Lato-Italic.ttf
          style: italic
          weight: 300
        - asset: assets/fonts/Lato-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700
        - asset: assets/fonts/Lato-BlackItalic.ttf
          weight: 900



